### ISSUE TITLE
ERC-20 Listings

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer#1076]
What's the simplest way to get a V1 of this working?

- Only USDC, or currencies that support `transferWithAuthorization`

There seems to be two ways to do this:

1) Separated

For every listing, it has a currency. When querying listings, you choose the currency you want to filter by. Requires us to move away from using cached prices for sorting (can't cache for every currency). 

2) Integrated

For all non-ETH listings, continually figure out the conversion rate to ETH, and determine if it's the best listing or not, and sort by the converted ETH amount. Requires us to continually reprice, but sorting method mostly stays the same

**Comment by ptrwtts** [comment]
Here's where I think we landed:

- Only support for Seaport listings
- Fill directly on Seaport contract (one or multiple), with referrer
- Integrated, where we are re-calculating the "best" price on an interval, so existing APIs work mostly as-is

**Comment by georgeroman** [comment]
A few other things to consider:
- Will these orders be aggregated? If that's the case then this is a breaking change (since all integrators assume the price is ETH/WETH). We should probably think how to handle that.
- At the API level we will simply disallow sweeping if that involves an ERC20 listing across exchanges (since that would require a router approval), how will the UI handle that?

**Comment by ptrwtts** [comment]
- In old API versions, filter non-ETH listings, so that clients won't try to fill them
- In new clients, they should prevent trying to fill multiple listings in different currencies

Separately, any time we are returning prices, we should always return the following, inspired by Zora:
- chainPrice
- nativePrice
- usdPrice
